version: "3.8"

services:
  api:
    build:
      context: ./app
    container_name: flask_api
    ports:
      - "${API_PORT:-5001}:5000"
    volumes:
      - ./app:/app
    networks:
      - api_network
      - shared_network # Shared network with db
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017
      - APP_ENV=${APP_ENV:-development}

  db:
    image: mongo:6.0
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "${DB_PORT:-27017}:27017"
    networks:
      - db_network
      - shared_network # Shared network with api

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_express
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    networks:
      - db_network
    depends_on:
      - db

networks:
  api_network:
    driver: bridge
  db_network:
    driver: bridge
  shared_network: # Shared network for db and api
    driver: bridge

volumes:
  mongo_data:
